### ISSUE TITLE
Unable to install version 3.12.1 using Cocoapods

### ISSUE THREAD

**Issue by rhuariglen1** [clemensg/sqlite3pod#4] opened 2016-04-19 13:53 UTC
`[!] Error installing sqlite3
[!] /usr/bin/curl -f -L -o /var/folders/dl/znb3wjyd20l18c3psf1wcv440000gn/T/d20160419-24271-188harc/file.zip https://www.sqlite.org/2016/sqlite-amalgamation-3120100.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found`

Getting this error when running 'pod update' on my project. Seems like the file doesnt exist on the server. Can also see that sqlite3 are at version 3.12.2, is there an update for your cocoapod available?

**Comment by clemensg** [comment] 2016-04-19 14:32
Thanks for the report, looks like the file was pulled from sqlite.org! Maybe it was removed due to the regression (https://www.sqlite.org/src/info/7d7525cb01b68) found in 3.12.0 and 3.12.1.

I'll upload the new version 3.12.2 immediately!

**Comment by rhuariglen1** [comment] 2016-04-19 14:46
Thanks, will let you know if this works once Cocoapods update the version on their website Still sitting at version 3.12.1

**Comment by clemensg** [comment] 2016-04-19 14:49
Hi, the build tests take a while but it is now finished: https://github.com/CocoaPods/Specs/commit/4bbc91f38eb58a781526637bda2735a85d763759

Should be available through CocoaPods now.

Please report back if it works for you. Thank you.

**Comment by rhuariglen1** [comment] 2016-04-19 14:49
Working now, thanks!

**Comment by clemensg** [comment] 2016-04-19 14:50
Great. I am closing this now.

**Closed by clemensg** 2016-04-19 14:50 UTC
